### PR TITLE
support remote connect/disconnect

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by doudou** [comment]
Please explain what this commit does *extensively* in the commit message, and write a test to demonstrate it.

**Comment by planthaber** [comment]
Before this, the api was unable to call connect/disconnect on components running on different nameservices as the name service was taken from the url for source **and** target, where the target could actually run on a different name service.

Test case cannot be done as this needs a distributed system.

**Comment by doudou** [comment]
> Before this, the api was unable to call connect/disconnect on components running on different nameservices as the name service was taken from the url for source and target, where the target could actually run on a different name service.

It still can't. You're not accessing a specific nameservice, you're just using Orocos.name_service which in no way is guaranteed to access the remote name service you're expecting.

> Test case cannot be done as this needs a distributed system.

Yes it can. Just create LocalNameService objects and register tasks with various names on them.

**Comment by planthaber** [comment]
>you're just using Orocos.name_service which in no way is guaranteed to access the remote name service you're expecting.

Well, the nameservice can be part of the parameter http://[...]/connect?to=otherhost/taskname&port=portname, this way Orocos.name_service.get "otherhost/taskname" is called.


> Yes it can. Just create LocalNameService objects and register tasks with various names on them.
i don't see how a LocalNameService can mimic an remote one that is only available on another host

**Comment by doudou** [comment]
> Well, the nameservice can be part of the parameter 

Fair point. Except that by calling Orocos.get directly instead of using the common resolution helpers, errors will be reported differently.

Best is really to split namespace from task, allow for a '*' namespace the same way than from the source task, and use the resolution helpers. Uniformity.

**Comment by planthaber** [comment]
Hmm, this was a infield hack i submitted as PR to a problem that already has an PR https://github.com/rock-core/tools-rest_api/pull/19

**Comment by doudou** [comment]
So, should we close this one ?

**Pull request closed without merging**
