### PR TITLE
convert to json when sending operation retrun values

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by doudou** [comment]
Tests ..... !

**Comment by planthaber** [comment]
ruby task contexts currently have no operation support...

**Comment by doudou** [comment]
That is what mocking is for

```
flexmock(ruby_task_context).should_receive(:callop).with(name_of_operation).
   once.and_return(typelib_value)
# Now verify that the typelib value is actually marshalled
```

**Comment by planthaber** [comment]
Hi tired that, but i was unsuccessful:
while flexmock works "locally"

``` ruby
flexmock(task).should_receive('operation').with("simplereturn").and_return(
                         flexmock().should_receive('callop').and_return(42).mock()      
                    )
                    op = task.operation("simplereturn")
                    puts op.pretty_inspect
                    puts op.callop
```

The web api still uses corba to receive the operation, which raises a "Orocos::InterfaceObjectNotFound" in orocos.rb/task_context.rb:558

resulting in an error 404 catched at rest_api/tasks/api.rb:95

**Pull request merged**
